### ISSUE TITLE
Scrum Update - 11/06/2022

### ISSUE THREAD

**Issue by tommo217** [RamitKataria/meeting-planner#11]

**Comment by merlin217** [comment]
Tom Mo (c9j7l)

(1) what you’ve worked on in the previous two weeks:
   - Implemented minimal frontend for the `New Meeting` page
   - Integrated frontend state with redux

(2) what you’ll be working on in the next two weeks:
  - Unify front-end design for `New Meeting` with other components
  - Finish implementing Redux store for `New Meeting` & make sure it works with `Availability Calendar`
  - _Stretch: component for importing existing Calendar_

(3) where you might have gotten stuck during the last two weeks:
  - Components were written with Redux in parallel, which may have slowed down progress, especially when trying to make controlled React components

**Comment by anan899** [comment]
Boyi Tang(May Tang t1n1b)
(1) what you’ve worked on in the previous two weeks:
- Working on the guest user login button
- Trying to add redux code to the "guest login button"

(2) what you’ll be working on in the next two weeks:
- Finishing Signup and Login page for both users and guests.
- Integrate the Signup and Login page with redux

(3) where you might have gotten stuck during the last two weeks:
- Misunderstanding of the onClick function of button and OnSubmit function of form, which makes the guest login form have bugs(eg. the form was submitted even the required field was not filled in)

**Comment by sophiechai** [comment]
Sophie Chai (l4h6k)

(1) what you’ve worked on in the previous two weeks:

- Include the NavBar component by using a Route component.
- Include styling for the NavBar

(2) what you’ll be working on in the next two weeks:

- upgrade the NavBar to include hover and expand features.
- maintain a consistent css styling amongst all pages.

(3) where you might have gotten stuck during the last two weeks:

- building the Routing from scratch. I could have use 3rd parties library to lighten up the work.
- navBar alignment and effects. Managed to find a solution after researching on couple forums.

**Comment by RamitKataria** [comment]
Ramit Kataria (x7x2b)

> 1. What did you work on this past iteration (2 weeks)?

- Implemented a simple availability picker component
- Discussed UX/UI workflow

> 2. What were any major issues/challenges you ran into?
- Making the table work with 1 onclick handler instead of 1 for each cell
- Implement dragging
- Consistent styling

> 3. What do you plan to work on for this coming iteration (2 weeks)?
- Have the availability picker fully functioning including support for viewing other people's availability and saving state in Redux
- Putting everything together to have a mostly finished frontend
- Implement a basic server so that we can have the dummy data there and have the frontend fetching the data instead of using data initialized in frontend
