### ISSUE TITLE
Scrum Update - 29/05/2022

### ISSUE THREAD

**Issue by RamitKataria** [RamitKataria/meeting-planner#5]
In the last 2 weeks, I suggested 2-3 ideas for our project, discussed with the team about which one to we should go for, came up with several requirements for the project and suggested the design of the website which we took some parts from to draw the rough sketch.

Our major challenges were:
- Deciding on an idea
- Consolidating on a common design for the sketch
- Scoping the project to somewhat challenge ourselves while keeping in mind the how much time we have

For the next 2 weeks, I plan to discuss with the team about the essential React components we need and assign some to each team member so we're done building most of the components.

CSID: x7x2b

**Comment by RamitKataria** [comment]
[Follow up comment]

**Comment by merlin217** [comment]
(1) what you’ve worked on in the previous two weeks:
   - Documented project outline & requirements in collaboration with group members. 
   - Brainstormed UI design of our product

(2) what you’ll be working on in the next two week:
  - Implement key UI components in React (Eg. ), with focus on functionality
  - _(Optional) Med-fi fidelity prototypes for UI design if needed_

(3) where you might have gotten stuck during the last two weeks:
  - Deciding on the scope of the project (which features should be minimal, standard or stretch)
  - Iterating on potential design sketches -- figuring out how to allow group members to communicate different design ideas to each other effectively.

**Comment by sophiechai** [comment]
1. What did you work on this past iteration (2 weeks)?
- Discussed and finalized on project topic and scope.
- Came up with 2-3 standard and stretched requirements.
- Discussed and merged prototype sketch.

2.  What were any major issues/challenges you ran into?
- Deciding on a project topic. We had different topic ideas initially. To narrow down to one, it took us a while and lots of elaboration so we can determine which idea is more feasible.
- Everyone understood the assignment but had different concepts and ideas of the UI and the specifics. Tom decided so each of us sketch a version of the UI we had in mind so we can merge them all together.

3. What do you plan to work on for this coming iteration (2 weeks)?
- Discuss the main components and structure of the app.
- Work on individual tasks that are assigned for project progress 2.

**Comment by anan899** [comment]
1. What I have done in the past two weeks(2 weeks)?
- Discussed our project's topic and scope with my teammates, and suggested 3 or 4 requirements for the project.
- Discussed and finalized the prototype sketch design with my teammates.

2. Major challenges
- Finalized the topic of our project. 
- Everyone had their own idea of the project's UI design, and it seemed quite hard for me to merge these versions of UI together. Finally we decided to use Sophie's design as our frame and added several features to her UI.

3. My plan for the following 2 weeks
- Implement the React components for our project.
- Finish the tasks for our project that are assigned to me.

**Comment by anan899** [comment]
cs id : t1n1b
